version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
  springbootapp:
    build: .
    container_name: student_container
    ports:
      - "8080:8080"
    links:
      - mongodb
